// Western RPG Character Data
const ARCHETYPES = {
    "Adventurer": { 
        core: ["DEX", "APP"], 
        occupations: ["Archaeologist", "Big Game Hunter", "Bounty Hunter", "Confidence Trickster", "Dilettante", "Entertainer", "Expressman/woman", "Gambler", "Gentleman/lady", "Gunfighter", "Hobo", "Journalist", "Outlaw", "Scout/Mountain Person", "Soldier/Warrior"], 
        bonusSkills: ["Climb", "Drive Coach/Wagon", "First Aid", "Fighting (any)", "Firearms (any)", "Gambling", "Jump", "Language Other (any)", "Mechanical Repair", "Ride", "Stealth", "Survival", "Rope Use", "Swim"], 
        talent: 'Always Onward!', 
        talentDesc: 'Each round you can choose to get a 20% bonus to any roll of your choice. Furthermore, when travelling, you can move an additional D3 hexes per session.' 
    },
    "Beefcake": { 
        core: ["STR"], 
        occupations: ["Bounty Hunter", "Cowboy/girl", "Entertainer", "Farmer", "Gunfighter", "Hired Muscle", "Lawman", "Outlaw", "Person of God", "Pugilist", "Sailor", "Scout/Mountain Person", "Soldier/warrior", "Tribe Member"], 
        bonusSkills: ["Climb", "Fighting (Brawl)", "Intimidate", "Listen", "Mechanical Repair", "Psychology", "Swim", "Throw"], 
        talent: 'Hard Hitter', 
        talentDesc: 'For the purposes of combat maneuvers and bonus damage, you count as having +1 to your Build. Furthermore, for each Build level more you have compared to an opponent, you gain advantage to combat maneuver against them.' 
    },
    "Bon Vivant": {
        core: ["SIZ"],
        occupations: ["Artist", "Author", "Big Game Hunter", "Butler", "Confidence Trickster", "Dilettante", "Entertainer", "Gambler", "Gentleman/lady", "Hobo", "Hooker", "Itinerant Worker", "Librarian", "Merchant", "Politician", "Rancher"],
        bonusSkills: ["Appraise", "Art/Craft (any)", "Charm", "Fast Talk", "Language Other (any)", "Listen", "Spot Hidden", "Psychology", "Gambling"],
        talent: "Living Life!",
        talentDesc: "You double the HP regained from whiskey and the sanity regained from other pleasures."
    },
    "Cold Blooded": { 
        core: ["INT"], 
        occupations: ["Bounty Hunter", "Confidence Trickster", "Doctor", "Gambler", "Gunfighter", "Hired Muscle", "Hooker", "Journalist", "Lawman", "Lawyer/Judge", "Merchant", "Outlaw", "Politician", "Pugilist", "Scientist/Engineer", "Soldier", "Spy", "Zealot"], 
        bonusSkills: ["Art/Crafts (Acting)", "Disguise", "Fighting (any)", "Firearms (any)", "First Aid", "Gambling", "History", "Intimidate", "Law", "Listen", "Mechanical Repair", "Psychology", "Stealth", "Survival", "Track", "Trap"], 
        talent: 'All According to Plan', 
        talentDesc: 'Once per encounter, you can count any success as a critical success.' 
    },
    "Egghead": {
        core: ["INT", "EDU"],
        occupations: ["Author", "Craftsperson", "Doctor", "Gambler", "Itinerant Worker", "Journalist", "Lawyer/Judge", "Librarian", "Minor", "Student/Teacher", "Scientist/Engineer"],
        bonusSkills: ["Anthropology", "Appraise", "Electrical Repair", "First Aid", "Gambling", "Language Other (any)", "Library Use", "Mechanical Repair", "Operate Heavy Machinery", "Science", "Trap"],
        talent: "Eureka!",
        talentDesc: "You can create Gadgets and the difficulty level for any relevant skill is reduced by 1."
    },
    "Explorer": { 
        core: ["DEX", "POW"], 
        occupations: ["Author", "Big Game Hunter", "Coachman/woman", "Dilettante", "Expressman/woman", "Gentleman/lady", "Hobo", "Itinerant Worker", "Person of God", "Merchant", "Miner", "Sailor", "Student/Teacher", "Scout", "Tribe member"], 
        bonusSkills: ["Animal Handling", "Anthropology", "Archaeology", "Climb", "Driving Coach/wagon", "Fighting (Brawl)", "First Aid", "Jump", "Language Other (any)", "Natural World", "Navigate", "Ride", "Rope Use", "Stealth", "Survival", "Track"], 
        talent: 'Born Traveler', 
        talentDesc: 'The difficulty level for Climb, Natural World, Navigate, Survival and Swim rolls is always reduced by 1 level. Furthermore, when you travel any HP lost due to hazards or the weather is halved.' 
    },
    "Femme Fatale": {
        core: ["APP", "INT"],
        occupations: ["Artist", "Bartender", "Bounty Hunter", "Confidence Trickster", "Dilettante", "Entertainer", "Gambler", "Gentleman/lady", "Hooker", "Journalist", "Librarian", "Outlaw", "Politician", "Spy"],
        bonusSkills: ["Art/Craft (Acting)", "Appraise", "Charm", "Disguise", "Drive Coach/wagon", "Fast Talk", "Fighting (Brawl)", "Firearms (Handgun)", "Gambling", "Listen", "Psychology", "Read Lips", "Rope Use", "Sleight of Hand", "Stealth", "Trap"],
        talent: "Irresistible",
        talentDesc: "Charm and Persuade rolls are always reduced by 1 level of difficulty. Furthermore, anyone who fails an opposed roll suffers disadvantage when targeting you."
    },
    "Hard Boiled": { 
        core: ["CON"], 
        occupations: ["Bounty Hunter", "Coachman/woman", "Cowboy/girl", "Farmer", "Gunfighter", "Hired Muscle", "Lawman", "Outlaw", "Person of God", "Pugilist", "Sailor", "Scout", "Soldier", "Zealot"], 
        bonusSkills: ["Fighting (Brawl)", "Firearms (any)", "Drive Coach/Wagon", "Fast Talk", "Intimidate", "Law", "Listen", "Locksmith", "Sleight of Hand", "Spot Hidden", "Rope Use", "Stealth", "Throw"], 
        talent: 'That all you got?', 
        talentDesc: 'You have to lose 75% of your HP in a round to gain a major wound and when you gain a major wound, you do not suffer from disadvantage.' 
    },
    "Hunter": { 
        core: ["INT", "CON"], 
        occupations: ["Big Game Hunter", "Bounty Hunter", "Cowboy/girl", "Dilettante", "Expressman/woman", "Lawman", "Miner", "Outlaw", "Scout", "Tribe Member", "Zealot"], 
        bonusSkills: ["Animal Handling", "Fighting (any)", "Firearms (any)", "First Aid", "Listen", "Natural World", "Navigate", "Spot Hidden", "Ride", "Rope Use", "Stealth", "Survival", "Swim", "Track", "Trap"], 
        talent: 'No Escape', 
        talentDesc: 'Track and Trap rolls are always reduced by 1 level of difficulty and you gain +1 to your Move Rate. When rolling to maintain stamina during chases, you increase the success level by 1.' 
    },
    "Mystic": { 
        core: ["POW"], 
        occupations: ["Artist", "Confidence Trickster", "Craftsperson", "Doctor", "Entertainer", "Gentleman/lady", "Hobo", "Person of God", "Student/Teacher", "Scientist/Engineer", "Tribe Member", "Zealot"], 
        bonusSkills: ["Art/Craft (any)", "Disguise", "History", "Language Other (any)", "Listen", "Natural World", "Occult", "Psychology", "Science", "Sleight of Hand", "Spot Hidden", "Stealth", "Track"], 
        talent: 'Powers', 
        talentDesc: 'Can use Magic (Medium, Telekinesis, Shamanic Magic, Witchcraft).' 
    },
    "Outsider": {
        core: ["INT", "CON"],
        occupations: ["Artist", "Craftsperson", "Dilettante", "Entertainer", "Farmer", "Expressman/woman", "Hobo", "Itinerant Worker", "Miner", "Person of God", "Sailor", "Scout", "Tribe Member", "Zealot"],
        bonusSkills: ["Art/Craft (any)", "Animal Handling", "Fighting (any)", "First Aid", "Intimidate", "Language Other (any)", "Listen", "Medicine", "Navigation", "Stealth", "Survival (any)", "Track"],
        talent: "Unorthodox Methods",
        talentDesc: "Once per encounter can reverse the roll of a D100 and when an ally fails a roll, the outsider can use the same characteristic or skill against the obstacle/hazard with advantage."
    },
    "Rogue": { 
        core: ["DEX", "APP"], 
        occupations: ["Artist", "Bartender", "Confidence Trickster", "Dilettante", "Entertainer", "Gambler", "Gentleman/lady", "Gunfighter", "Hobo", "Hooker", "Lawyer", "Outlaw", "Pugilist", "Spy"], 
        bonusSkills: ["Appraise", "Art/Craft (any)", "Charm", "Disguise", "Fast Talk", "Gambling", "Law", "Locksmith", "Psychology", "Read Lips", "Rope Use", "Sleight of Hand", "Spot Hidden", "Stealth", "Trap"], 
        talent: 'Scoundrel to The Bone', 
        talentDesc: 'Disguise, Fast Talk, Law, Sleight of Hand and Stealth rolls are always reduced by 1 level of difficulty.' 
    },
    "Scholar": { 
        core: ["EDU"], 
        occupations: ["Author", "Butler", "Dilettante", "Doctor", "Gentleman/lady", "Journalist", "Lawyer/judge", "Librarian", "Merchant", "Politician", "Student/Teacher", "Scientist/Engineer"], 
        bonusSkills: ["Accounting", "Appraise", "Anthropology", "Archaeology", "History", "Language Other (any)", "Law", "Library Use", "Medicine", "Natural World", "Occult", "Psychology", "Science"], 
        talent: 'Um, Actually', 
        talentDesc: 'INT and EDU rolls are always reduced by 1 level of difficulty. Furthermore, when you assist someone and you succeed on an INT or EDU roll, grant an additional +30% success chance.' 
    },
    "Steadfast": { 
        core: ["CON"], 
        occupations: ["Butler", "Cowboy/girl", "Craftsperson", "Doctor", "Expressman/woman", "Farmer", "Gentleman/lady", "Gunfighter", "Hobo", "Journalist", "Lawman", "Person of God", "Politician", "Pugilist", "Soldier", "Tribe Member"], 
        bonusSkills: ["Accounting", "Drive Coach/Wagon", "Fighting (any)", "Firearms (Handgun)", "First Aid", "History", "Intimidate", "Law", "Natural World", "Navigate", "Persuade", "Psychology", "Ride", "Spot Hidden", "Survival"], 
        talent: 'Bulwark of Justice', 
        talentDesc: 'If an ally suffered a major wound or is dying, gain advantage to all rolls. Once per encounter, if an ally within Move Rate is being targeted, you may choose to become the target instead.' 
    },
    "Swashbuckler": {
        core: ["DEX", "APP"],
        occupations: ["Artist", "Big Game Hunter", "Dilettante", "Entertainer", "Gambler", "Gentleman/lady", "Gunfighter", "Journalist", "Lawman", "Outlaw", "Sailor"],
        bonusSkills: ["Art/Craft (any)", "Charm", "Climb", "Dodge", "Fighting (any)", "Jump", "Language Other (any)", "Mechanical Repair", "Navigate", "Rope Use", "Stealth", "Swim", "Throw"],
        talent: "Dazzling Heroics",
        talentDesc: "So long as you are at full HP, you have advantage on all rolls. Opponents suffer disadvantage when targeting you, unless you suffer from a major wound or are dying."
    },
    "Thrill Seeker": {
        core: ["DEX", "POW"],
        occupations: ["Big Game Hunter", "Bounty Hunter", "Confidence Trickster", "Dilettante", "Entertainer", "Expressman/woman", "Gambler", "Gunfighter", "Hired Muscle", "Hooker", "Outlaw", "Pugilist", "Sailor", "Soldier", "Spy", "Zealot"],
        bonusSkills: ["Art/Craft (any)", "Charm", "Climb", "Drive Coach/Wagon", "Fast Talk", "Gambling", "Jump", "Mechanical Repair", "Navigate", "Ride", "Stealth", "Survival", "Swim", "Throw"],
        talent: "Adrenaline Junkie",
        talentDesc: "When you suffer from a major wound, you have advantage to all your rolls until it is healed. If you are Dying, you count all rolls as being reduced by 1 difficulty level."
    },
    "Two-Fisted": {
        core: ["STR", "SIZ"],
        occupations: ["Big Game Hunter", "Bounty Hunter", "Coachman/woman", "Cowboy/girl", "Gunfighter", "Hired Muscle", "Outlaw", "Pugilist", "Scout", "Soldier", "Zealot", "Tribe Member"],
        bonusSkills: ["Dodge", "Drive Coach/Wagon", "Fighting (Brawl)", "Firearms (any)", "Intimidate", "Listen", "Mechanical Repair", "Spot Hidden", "Swim", "Throw"],
        talent: "Get Some!",
        talentDesc: "When fighting back, you need the same level of success or better to hit the opponent. Furthermore, when you roll an extreme success, you deal extreme damage, even when fighting back."
    }
};

const OCCUPATIONS = {
    'Artist': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.POW * 2), skillPointsText: "EDU x 2 + (DEX x 2 or POW x 2)", crRange: [6, 60], skills: ['Art/Craft (any)', 'History', 'Library Use', 'Psychology', 'Spot Hidden', 'Sleight of Hand', 'any two other skills'] },
    'Author': { skillPointsFormula: (chars) => chars.EDU * 4, skillPointsText: "EDU x 4", crRange: [9, 30], skills: ['Art (Literature)', 'History', 'Library Use', 'Natural World or Occult', 'Other Language', 'Own Language', 'Psychology', 'any one other skill'] },
    'Bartender': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.APP * 2, skillPointsText: "EDU x 2 + APP x 2", crRange: [8, 25], skills: ['Accounting', 'two interpersonal skills (Charm, Fast Talk, Intimidate, or Persuade)', 'Fighting (Brawl)', 'Listen', 'Psychology', 'Spot Hidden', 'any one other skill'] },
    'Big Game Hunter': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (DEX x 2 or STR x 2)", crRange: [20, 50], skills: ['Firearms', 'Listen or Spot Hidden', 'Natural World', 'Navigate', 'Other Language or Survival (any)', 'Stealth', 'Track', 'Trap'] },
    'Bounty Hunter': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (DEX x 2 or STR x 2)", crRange: [9, 30], skills: ['Drive Coach/Wagon', 'Fighting or Firearms (any)', 'one interpersonal skill (Fast Talk, Charm, Intimidate, or Persuade)', 'Law', 'Psychology', 'Rope Use', 'Track', 'Trap', 'Stealth'] },
    'Butler': { skillPointsFormula: (chars) => chars.EDU * 4, skillPointsText: "EDU x 4", crRange: [9, 40], skills: ['Accounting or Appraise', 'Art/Craft (any)', 'First Aid', 'Listen', 'Other Language', 'Psychology', 'Spot Hidden', 'any two other skills'] },
    'Coachman/woman': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.DEX * 2, skillPointsText: "EDU x 2 + DEX x 2", crRange: [10, 40], skills: ['Drive Coach/Wagon', 'two interpersonal skills (Charm, Fast Talk, Intimidate, or Persuade)', 'Listen', 'Mechanical Repair', 'Navigate', 'Ride', 'Spot Hidden', 'any one other skill'] },
    'Confidence Trickster': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.APP * 2, skillPointsText: "EDU x 2 + APP x 2", crRange: [10, 80], skills: ['Disguise', 'Listen', 'Psychology', 'Sleight of Hand', 'Spot Hidden', 'two interpersonal skills (Charm, Fast Talk, Intimidate, or Persuade)'] },
    'Cowboy/girl': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (DEX x 2 or STR x 2)", crRange: [9, 20], skills: ['Firearms (Handgun or Shotgun)', 'First Aid', 'Jump', 'Natural World', 'Ride', 'Rope Use', 'Track'] },
    'Craftsperson': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.DEX * 2, skillPointsText: "EDU x 2 + DEX x 2", crRange: [10, 70], skills: ['Accounting', 'Art/Craft (any)', 'Drive (Wagon)', 'Mechanical Repair', 'Persuade', 'any three other skills'] },
    'Dilettante': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'APP' ? chars.APP * 2 : chars.CON * 2), skillPointsText: "EDU x 2 + (APP x 2 or CON x 2)", crRange: [50, 99], skills: ['Art/Craft (any)', 'Listen', 'Other Language', 'Ride', 'one interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade)', 'any three other skills'] },
    'Doctor': { skillPointsFormula: (chars) => chars.EDU * 4, skillPointsText: "EDU x 4", crRange: [30, 80], skills: ['Accounting', 'First Aid', 'Medicine', 'Other Language', 'Psychology', 'Science', 'any one other skill'] },
    'Entertainer': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.APP * 2, skillPointsText: "EDU x 2 + APP x 2", crRange: [9, 60], skills: ['Art/Craft (e.g. Actor, Singer, Comedian, Musician etc.)', 'Disguise', 'two interpersonal skills (Charm, Fast Talk, Intimidate, or Persuade)', 'Listen', 'Psychology', 'any two other skills'] },
    'Expressman/woman': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.CON * 2), skillPointsText: "EDU x 2 + (DEX x 2 or CON x 2)", crRange: [20, 60], skills: ['Accounting', 'Drive (Wagon or Stagecoach)', 'Fast Talk', 'Firearms (any)', 'Mechanical Repair', 'Natural World', 'Navigate', 'Ride'] },
    'Farmer': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'STR' ? chars.STR * 2 : chars.CON * 2), skillPointsText: "EDU x 2 + (STR x 2 or CON x 2)", crRange: [9, 50], skills: ['Art/Craft (Farming)', 'Firearms (Rifle and Shotgun)', 'Drive (Wagon)', 'First Aid', 'Jump', 'Mechanical Repair', 'Natural World', 'Ride', 'Rope Use'] },
    'Gambler': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'POW' ? chars.POW * 2 : chars.DEX * 2), skillPointsText: "EDU x 2 + (POW x 2 or DEX x 2)", crRange: [10, 60], skills: ['Accounting', 'Gambling', 'Listen', 'Psychology', 'Sleight of Hand', 'Spot Hidden', 'one interpersonal skill (Charm, Fast Talk, or Persuade)', 'one other skill'] },
    'Gentleman/lady': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.APP * 2, skillPointsText: "EDU x 2 + APP x 2", crRange: [40, 90], skills: ['Art/Craft (any)', 'two interpersonal skills (Charm, Fast Talk, Intimidate, or Persuade)', 'Firearms (Handguns)', 'Gambling', 'History', 'Other Language', 'Navigate', 'Ride'] },
    'Gunfighter': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.DEX * 2, skillPointsText: "EDU x 2 + DEX x 2", crRange: [9, 70], skills: ['Dodge', 'Fighting (Brawl)', 'Firearms (any)', 'Ride', 'Stealth', 'Spot Hidden', 'Track', 'one interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade)'] },
    'Hired Muscle': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.STR * 2, skillPointsText: "EDU x 2 + STR x 2", crRange: [5, 30], skills: ['Dodge', 'Drive Coach/wagon', 'Fighting (any)', 'Firearms (handguns and shotguns)', 'two interpersonal skills (Charm, Fast Talk, Intimidate, or Persuade)', 'Psychology', 'Stealth', 'Spot Hidden'] },
    'Hobo': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'CON' ? chars.CON * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (CON x 2 or STR x 2)", crRange: [0, 6], skills: ['Climb', 'Fast Talk', 'Jump', 'Listen', 'Natural World', 'Navigate', 'Stealth', 'any one other 2 skills'] },
    'Hooker': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.APP * 2, skillPointsText: "EDU x 2 + APP x 2", crRange: [5, 50], skills: ['Art/Craft (any)', 'Dodge', 'two interpersonal skills (Charm, Fast Talk, Intimidate, or Persuade)', 'Psychology', 'Sleight of hand', 'Stealth', 'any one other skill'] },
    'Itinerant Worker': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (DEX x 2 or STR x 2)", crRange: [0, 10], skills: ['Art/Craft (any)', 'Climb', 'Sleight of Hand', 'Mechanical Repair', 'Natural World', 'Navigate', 'any two other skills'] },
    'Journalist': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.INT * 2, skillPointsText: "EDU x 2 + INT x 2", crRange: [9, 30], skills: ['Art/Craft (e.g. Writing, Photography, etc.)', 'one interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade)', 'History', 'Library Use', 'Psychology', 'Spot Hidden', 'any two other skills'] },
    'Lawman/woman': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (DEX x 2 or STR x 2)", crRange: [20, 70], skills: ['Dodge', 'Fighting (Brawl)', 'Firearms (any)', 'Law', 'one interpersonal skill (Intimidate or Persuade)', 'Psychology', 'Ride', 'Spot Hidden', 'Track'] },
    'Lawyer/Judge': { skillPointsFormula: (chars) => chars.EDU * 4, skillPointsText: "EDU x 4", crRange: [20, 80], skills: ['Accounting', 'Law', 'Library Use', 'two interpersonal skills (Charm, Fast Talk, Intimidate, or Persuade)', 'Psychology', 'any two other skills'] },
    'Librarian': { skillPointsFormula: (chars) => chars.EDU * 4, skillPointsText: "EDU x 4", crRange: [9, 35], skills: ['Accounting', 'Library use', 'Other Language', 'Own Language', 'any four other skills'] },
    'Merchant': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'APP' ? chars.APP * 2 : chars.INT * 2), skillPointsText: "EDU x 2 + (APP x 2 or INT x 2)", crRange: [20, 60], skills: ['Accounting', 'Appraise', 'Psychology', 'Spot Hidden', 'two interpersonal skills (Charm, Fast Talk, Intimidate, or Persuade)', 'any two other skills'] },
    'Miner/Prospector': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (DEX x 2 or STR x 2)", crRange: [5, 60], skills: ['Climb', 'First Aid', 'Mechanical Repair', 'Natural World', 'Navigate', 'Science', 'Spot Hidden', 'any one other skill'] },
    'Nurse': { skillPointsFormula: (chars) => chars.EDU * 4, skillPointsText: "EDU x 4", crRange: [9, 30], skills: ['First Aid', 'Listen', 'Medicine', 'one interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade)', 'Psychology', 'Science', 'Spot Hidden'] },
    'Outlaw': { skillPointsFormula: (chars, choice) => { let statVal = 0; if (choice === 'APP') statVal = chars.APP * 2; else if (choice === 'DEX') statVal = chars.DEX * 2; else statVal = chars.INT * 2; return chars.EDU * 2 + statVal; }, skillPointsText: "EDU x 2 + (APP x 2 or DEX x 2 or INT x 2)", crRange: [6, 70], skills: ['Dodge', 'Fighting (any)', 'Firearms (any)', 'Ride', 'Stealth', 'one interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade)', 'Locksmith or Mechanical Repair', 'Psychology or Sleight of Hand', 'Spot Hidden'] },
    'Person of God': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.APP * 2, skillPointsText: "EDU x 2 + APP x 2", crRange: [9, 60], skills: ['History', 'Library Use', 'Listen', 'Occult', 'Other Language', 'one interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade)', 'Psychology', 'any one other skill'] },
    'Politician': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'APP' ? chars.APP * 2 : chars.INT * 2), skillPointsText: "EDU x 2 + (APP x 2 or INT x 2)", crRange: [10, 99], skills: ['History', 'Law', 'Listen', 'Psychology', 'Charm', 'Persuade', 'any two other skills'] },
    'Pugilist': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.STR * 2, skillPointsText: "EDU x 2 + STR x 2", crRange: [9, 60], skills: ['Dodge', 'Fighting (Brawl)', 'Intimidate', 'Jump', 'Psychology', 'Spot Hidden', 'any two other skills'] },
    'Rancher': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'INT' ? chars.INT * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (INT x 2 or STR x 2)", crRange: [50, 99], skills: ['Accounting', 'Law', 'Natural World', 'Persuade', 'Ride', 'Rope Use', 'Spot Hidden', 'any one other skill'] },
    'Sailor': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (DEX x 2 or STR x 2)", crRange: [9, 30], skills: ['Drive Coach/Wagon', 'Electrical or Mechanical Repair', 'Fighting (all)', 'Firearms (Rifles)', 'First Aid', 'Navigate', 'Rope Usen', 'Survival', 'Swim'] },
    'Student/Teacher': { skillPointsFormula: (chars) => chars.EDU * 4, skillPointsText: "EDU x 4", crRange: [10, 50], skills: ['Library Use', 'Other Language', 'Persuade or Intimidate', 'Psychology', 'Science', 'any three other skills'] },
    'Scientist/Engineer': { skillPointsFormula: (chars) => chars.EDU * 4, skillPointsText: "EDU x 4", crRange: [20, 80], skills: ['History', 'Law', 'Library Use', 'Mechanical Repair', 'Operate Heavy Machinery', 'any three other skills'] },
    'Scout/Mountains Person': { skillPointsFormula: (chars, choice) => { let statVal = 0; if (choice === 'DEX') statVal = chars.DEX * 2; else if (choice === 'STR') statVal = chars.STR * 2; else statVal = chars.CON * 2; return chars.EDU * 2 + statVal; }, skillPointsText: "EDU x 2 + (DEX x 2 or STR x 2 or CON x 2)", crRange: [0, 20], skills: ['Fighting (any)', 'Firearms (any)', 'First Aid', 'Natural World', 'Navigate', 'Ride', 'Rope Use', 'Stealth', 'Track', 'Trap'] },
    'Soldier/Warrior': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (DEX x 2 or STR x 2)", crRange: [10, 70], skills: ['Climb', 'Dodge', 'Fighting (any)', 'Firearms (Any)', 'First Aid', 'Mechanical Repair or Natural World', 'Stealth', 'Throw', 'any one other skill'] },
    'Spy': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'APP' ? chars.APP * 2 : chars.DEX * 2), skillPointsText: "EDU x 2 + (APP x 2 or DEX x 2)", crRange: [20, 60], skills: ['Art/Craft (Acting) or Disguise', 'Dodge', 'Firearms', 'Listen', 'Other Language', 'one interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade)', 'Psychology', 'Sleight of Hand', 'Stealth'] },
    'Tribe Member': { skillPointsFormula: (chars, choice) => chars.EDU * 2 + (choice === 'DEX' ? chars.DEX * 2 : chars.STR * 2), skillPointsText: "EDU x 2 + (DEX x 2 or STR x 2)", crRange: [0, 15], skills: ['Climb', 'Fighting (any)', 'Throw', 'Listen', 'Natural World', 'Occult', 'Spot Hidden', 'Swim', 'Survival'] },
    'Zealot': { skillPointsFormula: (chars) => chars.EDU * 2 + chars.POW * 2, skillPointsText: "EDU x 2 + POW x 2", crRange: [0, 30], skills: ['History', 'two interpersonal skills (Charm, Fast Talk, Intimidate, or Persuade)', 'Psychology', 'Stealth', 'and any three other skills'] }
};

const ALL_SKILLS = {
    'Accounting': {base: 5}, 'Animal Handling': {base: 5}, 'Anthropology': {base: 1}, 'Appraise': {base: 5}, 'Archaeology': {base: 1}, 
    'Art/Craft (Acting)': {base: 5}, 'Art/Craft (Fine Art)': {base: 1}, 'Art/Craft (Forgery)': {base: 1}, 'Art/Craft (Music)': {base: 5}, 
    'Art/Craft (Painting)': {base: 1}, 'Art/Craft (Photography)': {base: 0}, 'Art/Craft (Tinkering)': {base: 5}, 'Charm': {base: 15}, 
    'Climb': {base: 20}, 'Credit Rating': {base: 0}, 'Demolitions': {base: 1}, 'Disguise': {base: 5}, 'Dodge': {base: 0}, 
    'Drive Coach/Wagon': {base: 20}, 'Electrical Repair': {base: 0}, 'Fast Talk': {base: 5}, 'Fighting (Brawling)': {base: 25}, 
    'Fighting (Swords)': {base: 15}, 'Fighting (Indigenous Weapons)': {base: 20}, 'Firearms (Handguns)': {base: 20}, 
    'Firearms (Rifles)': {base: 25}, 'Firearms (Shotguns)': {base: 25}, 'Firearms (Missile Weapons)': {base: 15}, 
    'First Aid': {base: 30}, 'Gambling': {base: 10}, 'History': {base: 5}, 'Intimidate': {base: 15}, 'Jump': {base: 20}, 
    'Language Own': {base: 0}, 'Language Other': {base: 0, isSpecialty: true}, 'Law': {base: 5}, 'Library Use': {base: 20}, 
    'Listen': {base: 20}, 'Locksmith': {base: 1}, 'Mechanical Repair': {base: 10}, 'Medicine': {base: 1}, 'Medium': {base: 0}, 
    'Natural World': {base: 20}, 'Navigate': {base: 10}, 'Occult': {base: 5}, 'Operate Heavy Machinery': {base: 1}, 
    'Persuade': {base: 10}, 'Psychology': {base: 10}, 'Read Lips': {base: 1}, 'Ride': {base: 20}, 'Rope Use': {base: 5}, 
    'Science': {base: 1, isSpecialty: true}, 'Shamanic Magic': {base: 0}, 'Sleight of Hand': {base: 10}, 'Spot Hidden': {base: 25}, 
    'Stealth': {base: 20}, 'Survival': {base: 10}, 'Swim': {base: 20}, 'Telekinesis': {base: 0}, 'Throw': {base: 20}, 
    'Track': {base: 10}, 'Trap': {base: 10}, 'Witchcraft': {base: 0}
};

const SKILL_CATEGORIES = {
    "Fighting": ["Fighting (Brawling)", "Fighting (Swords)", "Fighting (Indigenous Weapons)"],
    "Firearms": ["Firearms (Handguns)", "Firearms (Rifles)", "Firearms (Shotguns)", "Firearms (Missile Weapons)", "Throw"],
    "Social": ["Charm", "Disguise", "Fast Talk", "Intimidate", "Persuade", "Psychology", "Read Lips"],
    "Knowledge": ["Accounting", "Anthropology", "Archaeology", "History", "Language Own", "Language Other", "Law", "Library Use", "Medicine", "Occult", "Science"],
    "Physical": ["Climb", "Jump", "Ride", "Stealth", "Swim"],
    "Survival & Perception": ["Animal Handling", "First Aid", "Listen", "Natural World", "Navigate", "Sleight of Hand", "Spot Hidden", "Survival", "Track"],
    "Technical & Craft": ["Appraise", "Art/Craft (Acting)", "Art/Craft (Fine Art)", "Art/Craft (Forgery)", "Art/Craft (Music)", "Art/Craft (Painting)", "Art/Craft (Photography)", "Art/Craft (Tinkering)", "Demolitions", "Electrical Repair", "Locksmith", "Mechanical Repair", "Operate Heavy Machinery"],
    "Psychic": ["Medium", "Telekinesis", "Shamanic Magic", "Witchcraft"],
    "Additional": ["Gambling", "Rope Use", "Trap", "Drive Coach/Wagon"],
    "Core": ["Credit Rating", "Dodge"]
};

const HINDRANCES = {
    'Blind (7)': {value: 7, desc: 'You can\'t see! You suffer -80% to any skill that requires sight. You increase the difficulty level of Spot Hidden rolls by 2.'},
    'Ailin\' (6)': {value: 6, desc: 'You suffer from an uncurable chronic illness. You have disadvantage to all STR and CON rolls and permanently have the Dying condition. At the start of each session, you must roll LUCK and CON. If you fail either, you lower STR and CON by D10.'},
    'Cursed (5)': {value: 5, desc: 'Whether real or imagined, you truly feel cursed. Nothing goes your way. Half your LUCK. When you fumble, the result is always really bad.'},
    'Thin-Skinned (5)': {value: 5, desc: 'Whenever you suffer damage, you suffer 1 additional damage. When making opposed rolls, always suffer disadvantage.'},
    'Grim Servant O\' Death (4)': {value: 4, desc: 'Wherever you go, death follows. Whenever you fumble, you target an ally. If no allies, an innocent bystander.'},
    'Death Wish (4)': {value: 4, desc: 'Your life ain\'t worth much and you know it. To flee, you must succeed in a Hard POW roll or stay in the fight. You cannot use Luck to avoid certain death.'},
    'Night Terrors (4)': {value: 4, desc: 'You have severe bad dreams. Must take a Hard POW roll at the beginning of each session. If you fail, either lose D6 sanity or suffer disadvantage to all rolls until next session.'},
    'Maimed (4)': {value: 4, desc: 'Start with a serious, detrimental, permanent injury (Lost leg, arm, eye, etc.).'},
    'Pacifist (4)': {value: 4, desc: 'You despise violence. To partake in any violence, must succeed in an Extreme POW roll. To retaliate, a Hard POW roll.'},
    'Loco (3)': {value: 3, desc: 'You never were all there. When you roll to see how much sanity you lose, roll the result twice and pick the highest one.'},
    'Heroic (3)': {value: 3, desc: 'As a noble soul, you never say no to a person in need. You can\'t let innocents get hurt or suffer, you will always intervene or help them, free of charge.'},
    'Tenderfoot (3)': {value: 3, desc: 'Every little cut and scrape makes you cry for your mama. Whenever you are not at full HP, suffer -10% to all rolls. With a major wound, difficulty of all rolls is increased by 1.'},
    'Trouble Magnet (3)': {value: 3, desc: 'You increase your fumble chance for all rolls by 5%.'},
    'Bloodthirsty (3)': {value: 3, desc: 'You enjoy seeing the light leave their eyes. You never take prisoners. Whenever you want to not kill a person, you must take a Hard POW roll.'},
    'Yellow-Belly (3)': {value: 3, desc: 'Not everyone\'s got cold ice-water in their veins. You increase the difficulty level of POW rolls by 1. Intimidation rolls always count as one level higher of success against you.'},
    'Mute (3)': {value: 3, desc: 'You cannot communicate by talking in any language. Increase difficulty level of Charm, Fast Talk and Persuade rolls by 1.'},
    'Big Britches (3)': {value: 3, desc: 'For being hit, increase your Build by 1. Move Rate is lowered by 1. When rolling to maintain stamina in chases, increase difficulty by 1.'},
    'Phobia (3)': {value: 3, desc: 'You have a random phobia. When you encounter it, you lose 2D10 sanity points and automatically suffer a Bout of Madness.'},
    'Drunkard (2/3)': {value: 3, desc: 'When you can drink, you do, unless you succeed in a Hard/Extreme POW roll. You always drink excessively.'},
    'Gamblin\' Man (2/3)': {value: 3, desc: 'When you can gamble, you do, unless you succeed in a Hard/Extreme POW roll. You can\'t help but push your luck.'},
    'All Thumbs (2)': {value: 2, desc: 'You\'re real clumsy. You suffer disadvantage to all Sleight of Hand, Locksmith, Operate Heavy Machinery and repair rolls. You cannot Quick Reload.'},
    'Obligation (2)': {value: 2, desc: 'You have responsibilities you must attend to (debt, family, etc.). Each week you lose credit, sanity, or other resources.'},
    'Shamed (2)': {value: 2, desc: 'Some past action haunts you. A place or faction has shamed you and they will likely shoot on sight.'},
    'Ugly (2)': {value: 2, desc: 'That is a face only a mama could love! You increase the difficulty level of APP, Charm and Persuade rolls by 1.'},
    'Lyin\' Eyes (2)': {value: 2, desc: 'Lies don\'t come easy to you. You suffer disadvantage when rolling for Disguises, Fast Talk, Gamble, Persuade, Intimidate and Charm.'},
    'Talisman (2)': {value: 2, desc: 'To call on your special talents, you need your lucky deck of cards, staff, etc. Only a character with the Powers talent can take this. You cannot use powers without it.'},
    'Old Ways Oath (2)': {value: 2, desc: 'You made an oath to forego modern technology and firearms.'},
    'Mean (2)': {value: 2, desc: 'Who pissed in your coffee?! You do not do things for free. Your reputation will usually suffer. You suffer disadvantage to Charm and Persuade rolls.'},
    'Wanted (2)': {value: 2, desc: 'You are wanted for a major crime (death sentence) by a major faction.'},
    'Miser (2)': {value: 2, desc: 'You half your current Spending Level. To part with cash, you must succeed a Hard POW roll.'},
    'Arrogant (2)': {value: 2, desc: 'You ARE the best. When someone bests you, you lose D6 sanity. When you defeat a worthy opponent, you must pass a Hard INT roll or let them live.'},
    'Bad Eyes (2)': {value: 2, desc: 'You just can\'t see that good. When you shoot beyond Point Blank range, you suffer disadvantage. You increase the difficulty level of Spot Hidden rolls by 1. Penalties ignored with glasses.'},
    'Laws O\' The West (2)': {value: 2, desc: 'You have a strict code. You keep your word, don\'t betray trust, and don\'t abuse/kill enemies. Acting un-gentlemanly costs sanity.'},
    'High Fallutin\' (2)': {value: 2, desc: 'You turn your nose up at those with a lower Credit Rating, increasing difficulty of social rolls by 1 against them. You lose sanity if your Spending Level isn\'t wealthy.'},
    'Hesitant (2)': {value: 2, desc: 'You always overthink your move, partner. You suffer disadvantage when determining DEX order at the beginning of combat.'},
    'Sensitive Constitution (1)': {value: 1, desc: 'When resisting poisons, diseases, or weather, you count as having rolled 1 level of success lower.'},
    'Loose Lips (1)': {value: 1, desc: 'You can\'t help but divulge your secrets to anyone on a failed INT roll.'},
    'Can\'t Swim (1)': {value: 1, desc: 'Whenever you hit the water, you sink like a rock. When submerged, you immediately start drowning.'},
    'Clueless (1)': {value: 1, desc: 'You suffer disadvantage to all EDU and relevant skill rolls for things you are not specialized in.'},
    'Curious (1)': {value: 1, desc: 'It killed the cat and might just kill you! To resist temptation to peek, go where you shouldn\'t, or ask when you shouldn\'t, you must pass a combined INT and POW roll.'},
    'Illiterate (1)': {value: 1, desc: 'You cannot read or write in any language.'},
    'Hankerin\' Habit (1)': {value: 1, desc: 'You have a consistent, daily habit that leaves you vulnerable and makes you predictable.'},
    'Hard of Hearin\' (1)': {value: 1, desc: 'WHAAAAT?! You increase the difficulty level of Listen rolls by 1.'},
    'Impulsive (1)': {value: 1, desc: 'You always escalate a situation if you fail a combined INT and POW roll.'},
    'Mild Mannered (1)': {value: 1, desc: 'You are not the most threatening individual. You suffer disadvantage to Intimidate and Fast Talk.'},
    'Vow (1)': {value: 1, desc: 'You swore to see something through and must constantly pursue it, or lose sanity.'},
    'Heavy Sleeper (1)': {value: 1, desc: 'A thunderstorm won\'t wake you. Anyone sneaking up on you gets a critical success.'},
    'Slowpoke (1)': {value: 1, desc: 'Molasses on a cold day move faster than you. You reduce your Move Rate by 1 (on foot).'},
    'Superstitious (1)': {value: 1, desc: 'Black cats should be shot if they cross your path. You suffer double sanity loss from strange encounters.'},
    'Tongue-Tied (1)': {value: 1, desc: 'You always flub your one-liners and insults. You suffer -10% to Charm, Fast Talk, Intimidate, Persuade and Languages.'}
};

const TALENTS = {
    'True Grit (7)': {value: 7, desc: 'Backing down just ain\'t in your blood partner! At the beginning of each session, you recover POW in the same way you do Luck. You have advantage to all POW rolls.'},
    'Fast as Lightnin\' (6)': {value: 6, desc: 'Faster than their own shadow. You count all DEX rolls as 1 level of success higher. Unless someone else has this talent, you always go first in combat and gain an additional action in the first round.'},
    'Meanest of the Bunch (5)': {value: 5, desc: 'You are one of the meanest hombres to walk the West. Whenever you do damage you roll an additional damage die of the same type.'},
    'Reputation (5)': {value: 5, desc: 'You already earned yourself quite the reputation in these parts. You start with the "Depend who\'s Asking" reputation and a nickname of choice.'},
    'Tough as Nails (4)': {value: 4, desc: 'You chew razor-blades for breakfast. You count all CON rolls as 1 level of success higher. You only ever take base damage, ignoring brutal and vicious damage.'},
    'Veteran o\' The West (4)': {value: 4, desc: 'You may distribute an additional 50 points in any Characteristic or skill.'},
    'Guts (3)': {value: 3, desc: 'You got some real sand in ya! You increase the success level of POW rolls by 1. Intimidation rolls always count as one level lower of success against you.'},
    'Dinero (3)': {value: 3, desc: 'Money talks. You increase your credit rating by 1 level. You can always wire "home" to ask for some money.'},
    'Duelist (3)': {value: 3, desc: 'Maybe not the fastest gun in the West, but you have won your fair share of duels. During a duel, you have advantage to all rolls.'},
    'Hip-Shooter (3)': {value: 3, desc: 'You can slap your gun fast and accurately. When levering or fanning, you suffer -5% to each consecutive shot, rather than -10%.'},
    'Level-Headed (3)': {value: 3, desc: 'Speed is overrated compared to keeping your cool. Opponents do not get the Outnumbered bonus against you. At the start of your turn, you may ignore one penalty.'},
    'Friends in High Places (3)': {value: 3, desc: 'It ain\'t about who you know, but who knows you. You have a powerful benefactor who can help you out.'},
    'Born Killer (3)': {value: 3, desc: 'You just got a talent for killin\' folk. You can re-roll a damage die each time you cause damage.'},
    'Sharpshooter (3)': {value: 3, desc: 'You can shoot a gnat\'s ass off from a hundred yards! As long as you do not move, you increase the success level of your ranged hits by 1 when using rifles.'},
    'Silver-Tongued (3)': {value: 3, desc: 'You truly have a gift for words! You have advantage to all Charm, Fast talk, Language and Persuade rolls.'},
    'Wilderness Man (3)': {value: 3, desc: 'You make the great outdoors civilized! You have advantage on all Natural World, Navigate, Survival, Track and Trap rolls. Difficult terrain does not slow you down.'},
    'Thick-Skinned (3)': {value: 3, desc: 'You can handle more than a little pain. Whenever you suffer damage, you subtract D3 from the received damage.'},
    'Agent (2)': {value: 2, desc: 'You work for one of the major factions. You can ask for reasonable support, but will have to work for their benefit.'},
    'Born in The Saddle (2)': {value: 2, desc: 'You have advantage on all riding and driving rolls.'},
    'Brawny (2)': {value: 2, desc: 'Your mama been feeding you well! You have advantage to STR and SIZ rolls.'},
    'Eagle Eyes (2)': {value: 2, desc: 'You increase the success level of Spot Hidden rolls by 1. You ignore the penalties to hit from weather effects.'},
    'Fisticuffs (2)': {value: 2, desc: 'Opponents do not get the Outnumbered and Armed vs Unarmed bonus against you in melee. You can re-roll 1 DB die each time you cause damage in melee.'},
    'Deadeye (2)': {value: 2, desc: 'Throats, eyes and hearts are the only thing worth shooting at. You cause brutal damage with ranged weapons.'},
    'Loyal Companion (2/3)': {value: 3, desc: 'You have a loyal pet/mount with its own traits and talents.'},
    'Tinkerer (2)': {value: 2, desc: 'You have advantage to all Locksmith, Operate Heavy Machinery and repair rolls.'},
    'Nerves O\' Steel (2)': {value: 2, desc: 'Nothing rattles you. You have advantage to POW rolls. When you lose sanity, you only lose half.'},
    'Nimble (2)': {value: 2, desc: 'When you dive for cover, you can still move and do not suffer disadvantage to your next roll.'},
    'Purty (2)': {value: 2, desc: 'What\'s cookin\' good lookin\'? You have advantage to APP and Charm rolls.'},
    'Quickdraw (2)': {value: 2, desc: 'Not quite fast, but quite quick. You gain +50% DEX roll to determine who goes first in combat (including duels).'},
    'Big Swings (2)': {value: 2, desc: 'Your Damage Bonus causes brutal damage.'},
    'Speed Loader (2)': {value: 2, desc: 'When you Quick Reload, load DEX/10 bullets or shells in your gun and shoot (with no disadvantage).'},
    'Ambidextrous (1)': {value: 1, desc: 'You do not suffer penalties for shooting with your off-hand.'},
    'Animal Lover (1)': {value: 1, desc: 'Animals can sense your good nature. You count all Animal Handling rolls as 1 level of success higher.'},
    'Belongin\'s (1)': {value: 1, desc: 'In addition to anything you might buy, you may choose to own a special item (About 15$ limit).'},
    'Eavesdropper (1)': {value: 1, desc: 'You increase the success level of Listen rolls by 1.'},
    'Gallows Humor (1)': {value: 1, desc: 'Some people just laugh at the Grim Reaper. If you lose sanity, you can roll Charm or Fast Talk. If you succeed, you and nearby allies only lose half.'},
    'Card Sharp (1)': {value: 1, desc: 'Little bit of talent, little bit of cheating. You have advantage on Gamble and Sleight of Hand rolls.'},
    'Keen (1)': {value: 1, desc: 'You notice the little things. You have advantage to Spot Hidden, Track and Listen.'},
    'Kemosabe (1)': {value: 1, desc: 'You do not suffer (social) penalties when interacting with a group as an "outsider".'},
    'Fate\'s Favored (1/2/3)': {value: 3, desc: 'Gain +10/+20/+30 Luck points to your maximum.'},
    'Fleet-Footed (1)': {value: 1, desc: 'You gain +1 to your Move Rate (on foot).'},
    'Light Sleeper (1)': {value: 1, desc: 'The slightest twig-crack wakes you. When sleeping, anyone sneaking up on you must succeed a Hard stealth roll.'},
    'Locked and Loaded (1)': {value: 1, desc: 'In the first round of combat, you cannot fumble.'},
    'Iron Liver (1)': {value: 1, desc: 'If your liver could absorb bullets like it does whiskey, you\'d be immortal. You always count CON rolls against alcohol as 1 level of success higher.'},
    'Gift of Gab (1)': {value: 1, desc: 'You got a real knack for entertaining and story-telling. You count all Fast Talk rolls as 1 level of success higher.'},
    'Evil Eye (1)': {value: 1, desc: 'Your eyes just got that killer\'s edge. You have advantage to Intimidation rolls. In a duel Stare Down, you count your roll as 1 level of success higher.'},
    'Luck O\' The Irish (1)': {value: 1, desc: 'When you use "My Hat!", you lose D3 slots worth of items, rather than D6.'},
    'Mule Man (1)': {value: 1, desc: 'You can carry an additional 3 slots.'},
    'War Cry (1)': {value: 1, desc: 'Once per encounter, roll Intimidation. If you win, opponents suffer disadvantage to their next actions.'},
    'Ruthless (1)': {value: 1, desc: 'You done worse than most and aren\'t easily impressed. You do not lose sanity for killing, torturing or seeing gruesome sights.'}
};
